module.exports = {
  JWT_EXPIRY: "7d",
  PASSWORD_MIN_LENGTH: 6,
  PROJECT_NAME_MAX_LENGTH: 100,
  TASK_TITLE_MAX_LENGTH: 200,
  TASK_DESCRIPTION_MAX_LENGTH: 2000,
  PROJECT_DESCRIPTION_MAX_LENGTH: 500,
  RATE_LIMIT_WINDOW: 15 * 60 * 1000, 
  RATE_LIMIT_MAX_REQUESTS: 100,
  AUTH_RATE_LIMIT_MAX: 5,
  AI_RATE_LIMIT_MAX: 20,
  NOTIFICATION_POLL_INTERVAL: 30000, 
};
